# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: s3cmd
        uses: s3-actions/s3cmd@v2.0.1
        with:
          provider: digitalocean
          region: "atl1"
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
      - uses: actions/checkout@v4
      - name: Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Check
        run: deno task check
      - name: Test
        run: deno task test
      - name: Build
        run: deno task build
      - name: Sync S3
        run: s3cmd sync --recursive --acl-public static s3://billfrye
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        if: ${{ success() && github.ref_name == 'main' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
